### ISSUE TITLE
MarvelApiClient synchronously calls

### ISSUE THREAD

**Issue by erikjhordan-rey** [Karumi/MarvelApiClientAndroid#13]
Hi guys! I've been reading your code specifically **MarvelApiClient** and I can't understand why the api calls are executed synchronously?, really I would like to understand the motivation.

¿Why you decided to do it this way?
How decide that the api calls should not be asynchronously?

What do you think about this [ mini famous disclaimer](https://futurestud.io/tutorials/retrofit-synchronous-and-asynchronous-requests)? 

`"synchronous requests can be the reason of app crashes on Android greater or equal than 4.0. You’re going to get a`NetworkOnMainThreadException`error".`

Maybe if the api call was inside an [IntentService](https://developer.android.com/reference/android/app/IntentService.html) it makes sense to me that's why I would like to know the motivation.

thank you for your awesome contributions are really cool!

**Comment by Serchinastico** [comment]
Hi @erikcaffrey 

It's our understanding that API clients are not responsible for where are they being executed. In this way, callers have the flexibility to decide if they are going to use a queue, an executor or whatever they want to use.

Thanks for your support!
