### ISSUE TITLE
Where should I declare MarvelApiConfig ?

### ISSUE THREAD

**Issue by sbis04** [Karumi/MarvelApiClientAndroid#19]
Where and in which file should I put this line:

MarvelApiConfig marvelApiConfig = new MarvelApiConfig.Builder(publicKey, privateKey).debug().build();

**Comment by sbis04** [comment]
Where and in which file should I put this line:

MarvelApiConfig marvelApiConfig = new MarvelApiConfig.Builder(publicKey, privateKey).debug().build();

**Comment by gupta-shrinath** [comment]
What this line basically does is that it takes your private and public key of marvel account and attaches it to the marvel query you are going to execute

**Comment by pedrovgs** [comment]
@sbis04 wherever you initialize your marvel api client.
